import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Kunal",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Bittu",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      //_id: "1",
      name: "Ganesha glass art",
      slug: "ganesha-glass-art",
      category: "Glass",
      image: "/images/glass_1.jpg", // 679px × 829px
      price: 120,
      countInStock: 0,
      rating: 4.5,
      numReviews: 10,
      description: "high quality art",
      location: "pune",
      artist: "NA",
      weight: 100,
      made_time: 15,
      mode: "new arrival",
      packing_size: "NA",
    },
    {
      //_id: "2",
      name: "Cushion jute art",
      slug: "cushion-jute-art",
      category: "Jute",
      image: "/images/jute_1.jpg", // 679px × 829px
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality art",
      location: "west bengal",
      artist: "NA",
      weight: 100,
      made_time: 15,
      mode: "best seller",
      packing_size: "NA",
    },
    {
      //_id: "3",
      name: "Bag jute art",
      slug: "bag-jute-art",
      category: "Jute",
      image: "/images/jute_2.jpg", // 679px × 829px
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality art",
      location: "west bengal",
      artist: "NA",
      weight: 100,
      made_time: 15,
      mode: "best seller",
      packing_size: "NA",
    },
    {
      //_id: "4",
      name: "Bag leather art",
      slug: "bag-leather-art",
      category: "Leather",
      image: "/images/leather_1.jpg", // 679px × 829px
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality art",
      location: "pune",
      artist: "NA",
      weight: 100,
      made_time: 15,
      mode: "new arrival",
      packing_size: "NA",
    },
    {
      //_id: "5",
      name: "lamp leather art",
      slug: "lamp-leather-art",
      category: "Leather",
      image: "/images/leather_2.jpg", // 679px × 829px
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality art",
      location: "west bengal",
      artist: "NA",
      weight: 100,
      made_time: 15,
      mode: "best seller",
      packing_size: "NA",
    },
    {
      //_id: "6",
      name: "Bird metal art",
      slug: "bird-metal-art",
      category: "Metal",
      image: "/images/metal_1.jpg", // 679px × 829px
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality art",
      location: "west bengal",
      artist: "NA",
      weight: 100,
      made_time: 15,
      mode: "best seller",
      packing_size: "NA",
    },
    {
      //_id: "7",
      name: "Lady metal art",
      slug: "lady-metal-art",
      category: "Metal",
      image: "/images/metal_2.jpg", // 679px × 829px
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality art",
      location: "west bengal",
      artist: "NA",
      weight: 100,
      made_time: 15,
      mode: "best seller",
      packing_size: "NA",
    },
    {
      //_id: "8",
      name: "Aarti metal art",
      slug: "aarti-metal-art",
      category: "Metal",
      image: "/images/metal_3.jpg", // 679px × 829px
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality art",
      location: "west bengal",
      artist: "NA",
      weight: 100,
      made_time: 15,
      mode: "best seller",
      packing_size: "NA",
    },
    {
      //_id: "9",
      name: "Dear metal art",
      slug: "dear-metal-art",
      category: "Metal",
      image: "/images/metal_4.jpg", // 679px × 829px
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality art",
      location: "pune",
      artist: "NA",
      weight: 100,
      made_time: 15,
      mode: "new arrival",
      packing_size: "NA",
    },
    {
      //_id: "10",
      name: "Small dear metal art",
      slug: "small-dear-metal-art",
      category: "Metal",
      image: "/images/metal_5.jpg", // 679px × 829px
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality art",
      location: "west bengal",
      artist: "NA",
      weight: 100,
      made_time: 15,
      mode: "best seller",
      packing_size: "NA",
    },
    {
      //_id: "11",
      name: "Turtle metal art",
      slug: "turtle-metal-art",
      category: "Metal",
      image: "/images/metal_6.jpg", // 679px × 829px
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality art",
      location: "west bengal",
      artist: "NA",
      weight: 100,
      made_time: 15,
      mode: "best seller",
      packing_size: "NA",
    },
    {
      //_id: "12",
      name: "Durga metal art",
      slug: "durga-metal-art",
      category: "Metal",
      image: "/images/metal_7.jpg", // 679px × 829px
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality art",
      location: "pune",
      artist: "NA",
      weight: 100,
      made_time: 15,
      mode: "new arrival",
      packing_size: "NA",
    },
    {
      //_id: "13",
      name: "Tea pot art",
      slug: "tea-pot-art",
      category: "Misc",
      image: "/images/misc_1.jpg", // 679px × 829px
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality art",
      location: "west bengal",
      artist: "NA",
      weight: 100,
      made_time: 15,
      mode: "best seller",
      packing_size: "NA",
    },
    {
      //_id: "14",
      name: "Kettle art",
      slug: "kettle-art",
      category: "Misc",
      image: "/images/misc_2.jpg", // 679px × 829px
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality art",
      location: "kashmir",
      artist: "NA",
      weight: 100,
      made_time: 15,
      mode: "new arrival",
      packing_size: "NA",
    },
    {
      //_id: "15",
      name: "Busket art",
      slug: "busket-art",
      category: "Misc",
      image: "/images/misc_3.jpg", // 679px × 829px
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality art",
      location: "west bengal",
      artist: "NA",
      weight: 100,
      made_time: 15,
      mode: "best seller",
      packing_size: "NA",
    },
    {
      //_id: "16",
      name: "Murti pottery art",
      slug: "murti-pottery-art",
      category: "Pottery",
      image: "/images/pottery_1.jpg", // 679px × 829px
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality art",
      location: "west bengal",
      artist: "NA",
      weight: 100,
      made_time: 15,
      mode: "best seller",
      packing_size: "NA",
    },
    {
      //_id: "17",
      name: "Pot pottery art",
      slug: "pot-pottery-art",
      category: "Pottery",
      image: "/images/pottery_2.jpg", // 679px × 829px
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality art",
      location: "west bengal",
      artist: "NA",
      weight: 100,
      made_time: 15,
      mode: "best seller",
      packing_size: "NA",
    },
    {
      //_id: "18",
      name: "Face pottery art",
      slug: "face-pottery-art",
      category: "Pottery",
      image: "/images/pottery_3.jpg", // 679px × 829px
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality art",
      location: "kashmir",
      artist: "NA",
      weight: 100,
      made_time: 15,
      mode: "new arrival",
      packing_size: "NA",
    },
    {
      //_id: "19",
      name: "Tiger stone art",
      slug: "tiger-stone-art",
      category: "Stone",
      image: "/images/stone_1.jpg", // 679px × 829px
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality art",
      location: "west bengal",
      artist: "NA",
      weight: 100,
      made_time: 15,
      mode: "best seller",
      packing_size: "NA",
    },
    {
      //_id: "20",
      name: "Musical wood art",
      slug: "musical-wood-art",
      category: "Wood",
      image: "/images/wood_1.jpg", // 679px × 829px
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality art",
      location: "west bengal",
      artist: "NA",
      weight: 100,
      made_time: 15,
      mode: "best seller",
      packing_size: "NA",
    },
    {
      //_id: "21",
      name: "Painted wood art",
      slug: "painted-wood-art",
      category: "Wood",
      image: "/images/wood_2.jpg", // 679px × 829px
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality art",
      location: "delhi",
      artist: "NA",
      weight: 100,
      made_time: 15,
      mode: "new arrival",
      packing_size: "NA",
    },
    {
      //_id: "22",
      name: "Lamp wood art",
      slug: "lamp-wood-art",
      category: "Wood",
      image: "/images/wood_3.jpg", // 679px × 829px
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality art",
      location: "west bengal",
      artist: "NA",
      weight: 100,
      made_time: 15,
      mode: "best seller",
      packing_size: "NA",
    },
  ],
};
export default data;
